### ISSUE TITLE
tuftool: panic when parsing malformed key source

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/tough#226]
I tried to run `tuftool root add-key` with a malformed key source and saw it panic.  This is with a tuftool built from the current `HEAD` of the `develop` branch (https://github.com/awslabs/tough/commit/969bf59be72112a1e355797d01f246dfba9a753e).

```
$ tuftool root add-key root.json aws-kms://tuf-junk --role root
thread 'main' panicked at 'byte index 1 is out of bounds of ``', /home/samuelkarp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/str/mod.rs:2052:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details>
<summary>With RUST_BACKTRACE=1</summary>

```
$ RUST_BACKTRACE=1 tuftool root add-key root.json aws-kms://tuf-junk --role root
thread 'main' panicked at 'byte index 1 is out of bounds of ``', /home/samuelkarp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/str/mod.rs:2052:47
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
  14: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}
  15: tuftool::source::parse_key_source
  16: <tuftool::root::Command as structopt::StructOptInternal>::augment_clap::{{closure}}
  17: clap::app::validator::Validator::validate_matched_args
  18: clap::app::validator::Validator::validate
  19: clap::app::parser::Parser::get_matches_with
  20: clap::app::parser::Parser::get_matches_with
  21: clap::app::parser::Parser::get_matches_with
  22: clap::app::App::get_matches_from_safe_borrow
  23: clap::app::App::get_matches
  24: tuftool::main
  25: std::rt::lang_start::{{closure}}
  26: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  27: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  28: std::panicking::try
             at src/libstd/panicking.rs:274
  29: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  30: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  31: main
  32: __libc_start_main
  33: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

The malformed-ness in the keysource is that I wrote `aws-kms://tuf-junk` instead of `aws-kms:///tuf-junk`.

Running with a correctly formed key source doesn't panic.

**Comment by iliana** [comment]
Likely cause: https://github.com/awslabs/tough/blob/969bf59be72112a1e355797d01f246dfba9a753e/tuftool/src/source.rs#L91-L92

**Comment by srgothi92** [comment]
> Likely cause:
> 
> https://github.com/awslabs/tough/blob/969bf59be72112a1e355797d01f246dfba9a753e/tuftool/src/source.rs#L91-L92

Do you have suggestion how to fix this :) ?

**Comment by samuelkarp** [comment]
> Do you have suggestion how to fix this :) ?

Probably checking that the length of the slice is >0 before attempting to index into it and making that an explicit error condition.
